# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\"0\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\"\x1e\n\x0eSearchResponse\x12\x0c\n\x04urls\x18\x03 \x03(\t\"T\n\rCommitRequest\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x12\n\nreplica_ip\x18\x05 \x01(\t\x12\x10\n\x08location\x18\x06 \x01(\t\x12\x0f\n\x07indices\x18\x07 \x03(\t\"\x1c\n\nCommitVote\x12\x0e\n\x06status\x18\x05 \x01(\x05\"/\n\x12\x43ommitStatusUpdate\x12\x19\n\x04\x63ode\x18\x06 \x01(\x0e\x32\x0b.CommitCode\"!\n\x0f\x41\x63knowledgement\x12\x0e\n\x06status\x18\x07 \x01(\x05\"\x16\n\x08IsMaster\x12\n\n\x02ip\x18\x01 \x01(\t\")\n\x12HealthCheckRequest\x12\x13\n\x0bhealthCheck\x18\x01 \x01(\t\"3\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"A\n\x0eReplicaRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x11\n\tmaster_ip\x18\x02 \x01(\t\x12\x0e\n\x06\x63reate\x18\x03 \x01(\x08\"\x1f\n\rReplicaStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05*\'\n\nCommitCode\x12\n\n\x06\x43OMMIT\x10\x00\x12\r\n\tROLL_BACK\x10\x01\x32>\n\x06Search\x12\x34\n\x0fSearchForString\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x00\x32\xb2\x01\n\rDatabaseWrite\x12\x39\n\x13WriteIndicesToTable\x12\x0e.CommitRequest\x1a\x10.Acknowledgement\"\x00\x12.\n\rQueryToCommit\x12\x0e.CommitRequest\x1a\x0b.CommitVote\"\x00\x12\x36\n\x0b\x43ommitPhase\x12\x13.CommitStatusUpdate\x1a\x10.Acknowledgement\"\x00\x32\x41\n\x0bHealthCheck\x12\x32\n\x05\x43heck\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponse2;\n\x0cLeaderNotice\x12+\n\x0cMasterChange\x12\t.IsMaster\x1a\x10.Acknowledgement2C\n\x0fReplicaCreation\x12\x30\n\rCreateReplica\x12\x0f.ReplicaRequest\x1a\x0e.ReplicaStatus2A\n\rReplicaUpdate\x12\x30\n\rUpdateReplica\x12\x0f.ReplicaRequest\x1a\x0e.ReplicaStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMITCODE']._serialized_start=518
  _globals['_COMMITCODE']._serialized_end=557
  _globals['_SEARCHREQUEST']._serialized_start=16
  _globals['_SEARCHREQUEST']._serialized_end=64
  _globals['_SEARCHRESPONSE']._serialized_start=66
  _globals['_SEARCHRESPONSE']._serialized_end=96
  _globals['_COMMITREQUEST']._serialized_start=98
  _globals['_COMMITREQUEST']._serialized_end=182
  _globals['_COMMITVOTE']._serialized_start=184
  _globals['_COMMITVOTE']._serialized_end=212
  _globals['_COMMITSTATUSUPDATE']._serialized_start=214
  _globals['_COMMITSTATUSUPDATE']._serialized_end=261
  _globals['_ACKNOWLEDGEMENT']._serialized_start=263
  _globals['_ACKNOWLEDGEMENT']._serialized_end=296
  _globals['_ISMASTER']._serialized_start=298
  _globals['_ISMASTER']._serialized_end=320
  _globals['_HEALTHCHECKREQUEST']._serialized_start=322
  _globals['_HEALTHCHECKREQUEST']._serialized_end=363
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=365
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=416
  _globals['_REPLICAREQUEST']._serialized_start=418
  _globals['_REPLICAREQUEST']._serialized_end=483
  _globals['_REPLICASTATUS']._serialized_start=485
  _globals['_REPLICASTATUS']._serialized_end=516
  _globals['_SEARCH']._serialized_start=559
  _globals['_SEARCH']._serialized_end=621
  _globals['_DATABASEWRITE']._serialized_start=624
  _globals['_DATABASEWRITE']._serialized_end=802
  _globals['_HEALTHCHECK']._serialized_start=804
  _globals['_HEALTHCHECK']._serialized_end=869
  _globals['_LEADERNOTICE']._serialized_start=871
  _globals['_LEADERNOTICE']._serialized_end=930
  _globals['_REPLICACREATION']._serialized_start=932
  _globals['_REPLICACREATION']._serialized_end=999
  _globals['_REPLICAUPDATE']._serialized_start=1001
  _globals['_REPLICAUPDATE']._serialized_end=1066
# @@protoc_insertion_point(module_scope)
