# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import search_pb2 as search__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearchStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchForString = channel.unary_unary(
                '/Search/SearchForString',
                request_serializer=search__pb2.SearchRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResponse.FromString,
                _registered_method=True)


class SearchServicer:
    """Missing associated documentation comment in .proto file."""

    def SearchForString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchForString': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchForString,
                    request_deserializer=search__pb2.SearchRequest.FromString,
                    response_serializer=search__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Search', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Search', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Search:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchForString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Search/SearchForString',
            search__pb2.SearchRequest.SerializeToString,
            search__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DatabaseWriteStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteIndicesToTable = channel.unary_unary(
                '/DatabaseWrite/WriteIndicesToTable',
                request_serializer=search__pb2.CommitRequest.SerializeToString,
                response_deserializer=search__pb2.Acknowledgement.FromString,
                _registered_method=True)
        self.QueryToCommit = channel.unary_unary(
                '/DatabaseWrite/QueryToCommit',
                request_serializer=search__pb2.CommitRequest.SerializeToString,
                response_deserializer=search__pb2.CommitVote.FromString,
                _registered_method=True)
        self.CommitPhase = channel.unary_unary(
                '/DatabaseWrite/CommitPhase',
                request_serializer=search__pb2.CommitStatusUpdate.SerializeToString,
                response_deserializer=search__pb2.Acknowledgement.FromString,
                _registered_method=True)


class DatabaseWriteServicer:
    """Missing associated documentation comment in .proto file."""

    def WriteIndicesToTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryToCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitPhase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseWriteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteIndicesToTable': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteIndicesToTable,
                    request_deserializer=search__pb2.CommitRequest.FromString,
                    response_serializer=search__pb2.Acknowledgement.SerializeToString,
            ),
            'QueryToCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryToCommit,
                    request_deserializer=search__pb2.CommitRequest.FromString,
                    response_serializer=search__pb2.CommitVote.SerializeToString,
            ),
            'CommitPhase': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitPhase,
                    request_deserializer=search__pb2.CommitStatusUpdate.FromString,
                    response_serializer=search__pb2.Acknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DatabaseWrite', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DatabaseWrite', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseWrite:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteIndicesToTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseWrite/WriteIndicesToTable',
            search__pb2.CommitRequest.SerializeToString,
            search__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryToCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseWrite/QueryToCommit',
            search__pb2.CommitRequest.SerializeToString,
            search__pb2.CommitVote.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitPhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DatabaseWrite/CommitPhase',
            search__pb2.CommitStatusUpdate.SerializeToString,
            search__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthCheckStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/HealthCheck/Check',
                request_serializer=search__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=search__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthCheckServicer:
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=search__pb2.HealthCheckRequest.FromString,
                    response_serializer=search__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HealthCheck', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('HealthCheck', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthCheck:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HealthCheck/Check',
            search__pb2.HealthCheckRequest.SerializeToString,
            search__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LeaderNoticeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MasterChange = channel.unary_unary(
                '/LeaderNotice/MasterChange',
                request_serializer=search__pb2.IsMaster.SerializeToString,
                response_deserializer=search__pb2.Acknowledgement.FromString,
                _registered_method=True)


class LeaderNoticeServicer:
    """Missing associated documentation comment in .proto file."""

    def MasterChange(self, request, context):
        """rpc by masterbackup to crawler to inform change in master
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaderNoticeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MasterChange': grpc.unary_unary_rpc_method_handler(
                    servicer.MasterChange,
                    request_deserializer=search__pb2.IsMaster.FromString,
                    response_serializer=search__pb2.Acknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LeaderNotice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LeaderNotice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeaderNotice:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MasterChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LeaderNotice/MasterChange',
            search__pb2.IsMaster.SerializeToString,
            search__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaCreationStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateReplica = channel.unary_unary(
                '/ReplicaCreation/CreateReplica',
                request_serializer=search__pb2.ReplicaRequest.SerializeToString,
                response_deserializer=search__pb2.ReplicaStatus.FromString,
                _registered_method=True)


class ReplicaCreationServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaCreationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReplica,
                    request_deserializer=search__pb2.ReplicaRequest.FromString,
                    response_serializer=search__pb2.ReplicaStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReplicaCreation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ReplicaCreation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaCreation:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReplicaCreation/CreateReplica',
            search__pb2.ReplicaRequest.SerializeToString,
            search__pb2.ReplicaStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaUpdateStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateReplica = channel.unary_unary(
                '/ReplicaUpdate/UpdateReplica',
                request_serializer=search__pb2.ReplicaRequest.SerializeToString,
                response_deserializer=search__pb2.ReplicaStatus.FromString,
                _registered_method=True)


class ReplicaUpdateServicer:
    """Missing associated documentation comment in .proto file."""

    def UpdateReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaUpdateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReplica,
                    request_deserializer=search__pb2.ReplicaRequest.FromString,
                    response_serializer=search__pb2.ReplicaStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReplicaUpdate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ReplicaUpdate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaUpdate:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReplicaUpdate/UpdateReplica',
            search__pb2.ReplicaRequest.SerializeToString,
            search__pb2.ReplicaStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
